engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  rubocop:
    enabled: true

ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
    - "**.scss"
    - "**.js"